/*
 * Microservicio de Contenido - UnderSounds
 *
 * Este microservicio gestiona el contenido multimedia y comercial del proyecto \"UnderSounds\", incluyendo albumes, canciones, generos, merchandising y noticias musicales.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"contenido/db"
	sw "contenido/go"
)

func main() {
	db.InitDatabase()
	defer db.DB.Close()
	routes := sw.ApiHandleFunctions{
		MerchandisingAPI: sw.MerchandisingAPI{DB: db.DB},
		PedidoAPI:        sw.PedidoAPI{DB: db.DB},
		SearchAPI:        sw.SearchAPI{DB: db.DB},
		NoticiasAPI:	  sw.NoticiasAPI{DB: db.DB},
	}

	log.Printf("Servidor iniciado")

	router := sw.NewRouter(routes)

	log.Fatal(router.Run(":8080"))
}
