/*
 * Microservicio de Contenido - UnderSounds
 *
 * Este microservicio gestiona el contenido multimedia y comercial del proyecto \"UnderSounds\", incluyendo albumes, canciones, generos, merchandising y noticias musicales.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Cancion struct {
	Id          int32  `json:"id,omitempty"`
	Nombre      string `json:"nombre"`
	Duracion    string `json:"duracion"`
	Album       int32  `json:"album"`
	ArchivoAudio []byte `json:"archivoAudio,omitempty"`
}
