/*
 * Microservicio de Contenido - UnderSounds
 *
 * Este microservicio gestiona el contenido multimedia y comercial del proyecto \"UnderSounds\", incluyendo albumes, canciones, generos, merchandising y noticias musicales.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AlbumDetalle struct {

	Id int32 `json:"id,omitempty"`

	Nombre string `json:"nombre"`

	Duracion string `json:"duracion"`

	Fecha string `json:"fecha"`

	Genero Genero `json:"genero"`

	Artista int32 `json:"artista"`

	NombreArtista string   `json:"nombreArtista"`

	Precio    float32 `json:"precio"`

	Canciones []Cancion `json:"canciones,omitempty"`
}
