/*
 * Microservicio de Contenido - UnderSounds
 *
 * Este microservicio gestiona el contenido multimedia y comercial del proyecto \"UnderSounds\", incluyendo albumes, canciones, generos, merchandising y noticias musicales.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Album struct {
	Id        int32  `json:"id,omitempty"`
	Nombre    string `json:"nombre"`
	Duracion  int32  `json:"duracion"` // segundos
	Imagen    []byte `json:"imagen,omitempty"`
	Fecha     string `json:"fecha"`
	Genero    Genero `json:"genero"`
	Artista   int32  `json:"artista"`
}

type CreateAlbumRequest struct {
	Nombre    string `json:"nombre" binding:"required"`
	Duracion  *int32 `json:"duracion"` // segundos (opcional)
	Imagen    []byte `json:"imagen,omitempty"`
	Fecha     string `json:"fecha"`
	Genero    int32  `json:"genero"`
	Artista   int32  `json:"artista"`
}

type UpdateAlbumRequest struct {
	Nombre    *string `json:"nombre"`
	Duracion  *int32  `json:"duracion"`
	Imagen    *[]byte `json:"imagen"`
	Fecha     *string `json:"fecha"`
	Genero    *int32  `json:"genero"`
	Artista   *int32  `json:"artista"`
}
