/*
 * Microservicio de Contenido - UnderSounds
 *
 * Este microservicio gestiona el contenido multimedia y comercial del proyecto \"UnderSounds\", incluyendo albumes, canciones, generos, merchandising y noticias musicales.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Noticia struct {
	Id int32 `json:"id,omitempty"`

	Titulo string `json:"titulo"`

	ContenidoHTML string `json:"contenidoHTML"`

	Fecha string `json:"fecha"`

	Autor int32 `json:"autor"`

	NombreAutor string `json:"nombreAutor,omitempty"`
}
