/*
 * Microservicio de Contenido - UnderSounds
 *
 * Este microservicio gestiona el contenido multimedia y comercial del proyecto \"UnderSounds\", incluyendo albumes, canciones, generos, merchandising y noticias musicales.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
	"github.com/gin-contrib/cors"
	"contenido/middleware"
	"github.com/gin-gonic/gin"
	"time"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method string
	// Pattern is the pattern of the URI.
	Pattern string
	// HandlerFunc is the handler function of this route.
	HandlerFunc gin.HandlerFunc
}

// NewRouter returns a new router.
func NewRouter(handleFunctions ApiHandleFunctions) *gin.Engine {
	return NewRouterWithGinEngine(gin.Default(), handleFunctions)
}

// NewRouter add routes to existing gin engine.
func NewRouterWithGinEngine(router *gin.Engine, handleFunctions ApiHandleFunctions) *gin.Engine {
	// Agregar el middleware CORS globalmente
	router.Use(cors.New(cors.Config{
		AllowOrigins:     []string{"http://localhost:5173"}, // Permite solo el frontend local en el puerto 5173
		AllowMethods:     []string{"GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"},
		AllowHeaders:     []string{"Origin", "Content-Type", "Authorization"},
		ExposeHeaders:    []string{"Content-Length"},
		AllowCredentials: true,
		MaxAge:           12 * time.Hour,
	}))

	// El middleware decide si aplicar autenticación basándose en el endpoint
	router.Use(func(c *gin.Context) {
		// Rutas públicas
		rutasPublicas := map[string]bool {
			"GET /albums": true,
			"GET /albums/:id": true,
			"GET /albums/:id/detalle": true,
			"GET /albums/:id/imagen": true,
			"GET /busqueda": true,
			"GET /canciones": true,
			"GET /canciones/album/:id": true,
			"GET /canciones/:id": true,
			"GET /canciones/:id/verAutores": true,
			"GET /canciones/:id/archivo": true,
			"GET /generos": true,
			"GET /merch": true,
			"GET /merch/:id": true,
			"GET /noticias/:id": true,
			"GET /noticias": true,
		}

		// Se formatea la clave de la ruta actual
		claveRuta := c.Request.Method + " " + c.FullPath()

		// Se comprueba si la ruta está entre las públicas
		if !rutasPublicas[claveRuta] {
			authMiddleware := middleware.Auth()
			authMiddleware(c)
		}

		c.Next()
	})

	for _, route := range getRoutes(handleFunctions) {
		if route.HandlerFunc == nil {
			route.HandlerFunc = DefaultHandleFunc
		}
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodPatch:
			router.PATCH(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}

	return router
}

// Default handler for not yet implemented routes
func DefaultHandleFunc(c *gin.Context) {
	c.String(http.StatusNotImplemented, "501 not implemented")
}

type ApiHandleFunctions struct {

	// Routes for the AlbumesAPI part of the API
	AlbumesAPI AlbumesAPI
	// Routes for the CancionesAPI part of the API
	CancionesAPI CancionesAPI
	// Routes for the GenerosAPI part of the API
	GenerosAPI GenerosAPI
	// Routes for the MerchandisingAPI part of the API
	MerchandisingAPI MerchandisingAPI
	// Routes for the NoticiasAPI part of the API
	NoticiasAPI NoticiasAPI
	// Routes for the PedidoAPI part of the API
	PedidoAPI PedidoAPI
	// Routes for the SearchAPI part of the API
	SearchAPI SearchAPI
}

func getRoutes(handleFunctions ApiHandleFunctions) []Route {
	return []Route{
		{
			"AlbumsGet",
			http.MethodGet,
			"/albums",
			handleFunctions.AlbumesAPI.AlbumsGet,
		},
		{
			"AlbumsIdDelete",
			http.MethodDelete,
			"/albums/:id",
			handleFunctions.AlbumesAPI.AlbumsIdDelete,
		},
		{
			"AlbumsIdGet",
			http.MethodGet,
			"/albums/:id",
			handleFunctions.AlbumesAPI.AlbumsIdGet,
		},
		{
			"AlbumsIdDetalleGet",
			http.MethodGet,
			"/albums/:id/detalle",
			handleFunctions.AlbumesAPI.AlbumsIdDetalleGet,
		},
		{
			"AlbumsIdImagenGet",
			http.MethodGet,
			"/albums/:id/imagen",
			handleFunctions.AlbumesAPI.AlbumsIdImagenGet,
		},
		{
			"AlbumsIdPatch",
			http.MethodPatch,
			"/albums/:id",
			handleFunctions.AlbumesAPI.AlbumsIdPatch,
		},
		{
			"AlbumsPost",
			http.MethodPost,
			"/albums",
			handleFunctions.AlbumesAPI.AlbumsPost,
		},
		{
			"CancionesGet",
			http.MethodGet,
			"/canciones",
			handleFunctions.CancionesAPI.CancionesGet,
		},
		{
			"CancionesAlbumIdGet",
			http.MethodGet,
			"/canciones/album/:id",
			handleFunctions.CancionesAPI.CancionesAlbumIdGet,
		},
		{
			"CancionesIdDelete",
			http.MethodDelete,
			"/canciones/:id",
			handleFunctions.CancionesAPI.CancionesIdDelete,
		},
		{
			"CancionesIdGet",
			http.MethodGet,
			"/canciones/:id",
			handleFunctions.CancionesAPI.CancionesIdGet,
		},
		{
			"CancionesIdPatch",
			http.MethodPatch,
			"/canciones/:id",
			handleFunctions.CancionesAPI.CancionesIdPatch,
		},
		{
			"CancionesIdVerAutoresGet",
			http.MethodGet,
			"/canciones/:id/verAutores",
			handleFunctions.CancionesAPI.CancionesIdVerAutoresGet,
		},
		{
			"CancionesPost",
			http.MethodPost,
			"/canciones",
			handleFunctions.CancionesAPI.CancionesPost,
		},
		{
			"CancionesIdArchivoGet",
			http.MethodGet,
			"/canciones/:id/archivo",
			handleFunctions.CancionesAPI.CancionesIdArchivoGet,
		},
		{
			"GenerosGet",
			http.MethodGet,
			"/generos",
			handleFunctions.GenerosAPI.GenerosGet,
		},
		{
			"MerchGet",
			http.MethodGet,
			"/merch",
			handleFunctions.MerchandisingAPI.MerchGet,
		},
		{
			"MerchIdDelete",
			http.MethodDelete,
			"/merch/:id",
			handleFunctions.MerchandisingAPI.MerchIdDelete,
		},
		{
			"MerchIdDisminuirStockMerchPatch",
			http.MethodPatch,
			"/merch/:id/disminuirStockMerch",
			handleFunctions.MerchandisingAPI.MerchIdDisminuirStockMerchPatch,
		},
		{
			"MerchIdGet",
			http.MethodGet,
			"/merch/:id",
			handleFunctions.MerchandisingAPI.MerchIdGet,
		},
		{
			"MerchIdPatch",
			http.MethodPatch,
			"/merch/:id",
			handleFunctions.MerchandisingAPI.MerchIdPatch,
		},
		{
			"MerchIdRecargarStockMerchPatch",
			http.MethodPatch,
			"/merch/:id/recargarStockMerch",
			handleFunctions.MerchandisingAPI.MerchIdRecargarStockMerchPatch,
		},
		{
			"MerchPost",
			http.MethodPost,
			"/merch",
			handleFunctions.MerchandisingAPI.MerchPost,
		},
		{
			"NoticiasIdGet",
			http.MethodGet,
			"/noticias/:id",
			handleFunctions.NoticiasAPI.NoticiasIdGet,
		},
		{
			"NoticiasGet",
			http.MethodGet,
			"/noticias",
			handleFunctions.NoticiasAPI.NoticiasGet,
		},
		{
			"NoticiasPost",
			http.MethodPost,
			"/noticias",
			handleFunctions.NoticiasAPI.NoticiasPost,
		},
		{
			"NoticiasIdDelete",
			http.MethodDelete,
			"/noticias/:id",
			handleFunctions.NoticiasAPI.NoticiasIdDelete,
		},
		{
			"BusquedaGet",
			http.MethodGet,
			"/busqueda",
			handleFunctions.SearchAPI.BusquedaGet,
		},
		{
			"PagoPedidoPost",
			http.MethodPost,
			"/pedido/pago",
			handleFunctions.PedidoAPI.Pago,
		},
	}
}
